variables:
  CPRAN_GIT: https://gitlab.com/cpran/plugin_

before_script:
  - pushd ..
  - rm -rf plugin_{testsimple,utils,selection}
  - git clone ${CPRAN_GIT}testsimple.git
  - git clone ${CPRAN_GIT}utils.git
  - git clone ${CPRAN_GIT}selection.git
  - popd
      
Praat 5.4.22:
  script:
    - prove -v --exec "praat-5.4.22 --ansi --pref-dir=../.."
  tags:
    - cpran
  allow_failure: true

Praat 6.0.03:
  script:
    - prove -v --exec "praat-6.0.03 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
  allow_failure: true

Praat 6.0.11:
  script:
    - prove -v --exec "praat-6.0.11 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
  allow_failure: true

Praat 6.0.13:
  script:
    - prove -v --exec "praat-6.0.13 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
  allow_failure: true

Praat 6.0.14:
  script:
    - prove -v --exec "praat-6.0.14 --ansi --pref-dir=../.. --run"
  tags:
    - cpran

